### ISSUE TITLE
A bout KCF  ,solution in the Dual Domain code .

### ISSUE THREAD

**Issue by yangkang779** [thias15/Context-Aware-CF-Tracking#2]
Thank you very much for your paper. The implementation of the code is only in the primal domain. There is no in dual domain code. How can I change it to a dual domain? Thank you.
       kf = conj(xf) .* xf; 
    
        kfn = zeros([size(xf) length(offset)]);
        for j=1:length(offset)
            %obtain a subwindow close to target for regression to 0
            patch = get_subwindow(im, pos+offset(j,:), window_sz);
            xfn = fft2(get_features(patch, features, cell_size, cos_window));
            kfn(:,:,:,j) = conj(xfn) .*xfn;
        end

        %Assumption: Features are independent
        num = bsxfun(@times, conj(xf),yf); 
        den = kf + lambda1 + lambda2.*sum(kfn,4);
        wf = num ./ den;
        
		if frame == 1,  %first frame, train with a single image
			model_wf = wf;
		else
			%subsequent frames, interpolate model
			model_wf = (1 - interp_factor) * model_wf + interp_factor * wf;
		end

**Comment by thias15** [comment]
Hello.

The dual formulation follows quite easily and the derivations are all in
the paper and supplementary material. The problem is that it will be much
slower as the primal solution for high dimensional features.

I have implemented the dual formulation for some trackers if I remember
correctly. Do you need it for single channel or multi channel features?

Matthias

**Comment by yangkang779** [comment]
My e-mail :yangkang779760348@gmail.com
Yes,I  need for multi channnel features ,
Can you send the dual formulation for KCF-CA with multi-channel features code to my mailbox? 
My e-mail :  yangkang779760348@gmail.com
I experimented with the code of the pirmal domain, but found that the hyperparameter λ2 needs to be adjusted, but I don't know how much the setting is appropriate. I will experiment a few more times, thank you very much for your work.

**Comment by Rheelt** [comment]
@thias15 Thank you for your contribution. Can you send me the dual domain code with multi-channel features? Thank you very much!
Or if you receive it, can you share it with me? Thank you. @yangkang779

**Comment by Rheelt** [comment]
My email : rheecoder@gmail.com

**Comment by yangkang779** [comment]
Hello,Can you provide mo for the  formulti channel features   in  the dual formulation for DCF code? Thanks.

**Comment by thias15** [comment]
Sorry for the late response. Check your email.
