### ISSUE TITLE
mexResize function compiled for the mac

### ISSUE THREAD

**Issue by ghost** [thias15/Context-Aware-CF-Tracking#3]
Thank you for the code.
I tried to run the code for on mac system but there is no compiled mex function for the mexResize.cpp 
is it possible for you to provide the compiled mex function for the mac OS?
I tried to install opencv and compile the mex files but never succeed

**Comment by thias15** [comment]
I'm sorry, but I don't use Mac. There should be a compiled mex file for Linux though. 

 

Matthias

 

Gesendet: Mittwoch, 08. August 2018 um 11:18 Uhr
Von: brezae <notifications@github.com>
An: thias15/Context-Aware-CF-Tracking <Context-Aware-CF-Tracking@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [thias15/Context-Aware-CF-Tracking] mexResize function compiled for the mac (#3)


Thank you for the code.
I tried to run the code for on mac system but there is no compiled mex function for the mexResize.cpp
is it possible for you to provide the compiled mex function for the mac OS?
I tried to install opencv and compile the mex files but never succeed
